### ISSUE TITLE
Error when attempting to mv directory

### ISSUE THREAD

**Issue by turbo124** [yunwei37/OpenAI-Continuous-Translator#3]
Seeing this error when the translations complete. Any idea what could be the cause?

```
INFO:root:Translation completed.
INFO:root:Saving translated file: local_repo/source/docs/api/authentication.md
INFO:root:File saved.
mv: cannot move 'local_repo/source' to './source': Directory not empty
```

here is the github actions .yml config

```yaml
name: Translate

on:
  issue_comment:
    types: [ created ]

jobs:
  gpt_translate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      - name: Commit files
        uses: yunwei37/OpenAI-Continuous-Translator@master
        with:
            git_repo_url: repo_url
            api_key: ${{ secrets.OPENAI_API_KEY }}
            source_language: English
            target_language: fr-CA
            i18n_surfix: fr-CA
            file_types: .md
            file_path_filter: "source/docs"

```
