### ISSUE TITLE
[Help Wanted]: file_path_filter 设置

### ISSUE THREAD

**Issue by yangtzech** [yunwei37/OpenAI-Continuous-Translator#4]
如果想将 git_repo_url 设置为原始仓库，但原始仓库有很多文件，这样会一次性翻译大量文件，所以想设置 file_path_filter 来一个一个测试，以翻译 README.md 为例，设置成 file_path_filter 分别为 `local_repo/README.md` 和 `README.md` 都没有作用，所以想请教下file_path_filter 应该怎样设置？

```
with:
          git_repo_url: https://github.com/radi-cho/awesome-gpt4
          api_key: ${{ secrets.OPENAI_API_KEY }}
          file_path_filter: local_repo/README.md
```
